// components/Footer.vue
<template>
	<footer>
		<div class="external-link-container">
			<a href="mailto:prokop.tony@gmail.com">
				<EmailSvg />
			</a>
			<a href="https://www.linkedin.com/in/tony-prokop/">
				<LinkedInSvg />
			</a>
			<a href="https://github.com/TonyProkop">
				<GithubSvg />
			</a>
		</div>
		<div class="tagline">© 2020 Tony Prokop Web Development</div>
	</footer>
</template>

<script>
import EmailSvg from '~/static/email.svg?inline';
import LinkedInSvg from '~/static/linkedin.svg?inline';
import GithubSvg from '~/static/github.svg?inline';

export default {
	components: {
		EmailSvg,
		LinkedInSvg,
		GithubSvg,
	}
}
</script>

<style scoped>
footer {
	display: flex;
	flex-direction: column;
	align-content: center;
	justify-content: center;
	text-align: center;
	padding: 6rem 0;
}

.tagline {
	margin-top: 6rem;
	font-size: 1.4rem;
}

.external-link-container {
	display: flex;
	margin: 0 auto;
}

.external-link-container a {
	width: 5rem;
	height: 5rem;
	border-radius: 100%;
	background-color: #3B4252;
	text-decoration: none;
	color: #D8DEE9;
	display: flex;
	align-items: center;
	justify-content: center;
	margin: 0 2rem;
}

.external-link-container a:hover {
	background-color: #434C5E;
}

.external-link-container a:active {
	background-color: #4C566A;
}
</style>

// src/app/components/Footer.tsx
"use client"

import * as React from "react"
import {
  Box,
  ButtonGroup,
  Container,
  Divider,
  Stack,
  Typography,
} from "@mui/material"
import Headshot from "./Headshot"
import MagneticButton from "./MagneticButton"
import PrimaryButton from "./PrimaryButton"
import Email from "./icons/Email"
import Github from "./icons/Github"
import Linkedin from "./icons/Linkedin"
import Phone from "./icons/Phone"
import RSS from "./icons/RSS"
import Leetcode from "./icons/Leetcode"

const Footer = () => {
  const links = [
    {
      component: <Email />,
      href: "mailto:prokop.tony@gmail.com",
    },
    {
      component: <Phone />,
      href: "tel:14029888222",
    },
    {
      component: <Github />,
      href: "https://github.com/TonyProkop",
    },
    {
      component: <Leetcode />,
      href: "https://leetcode.com/u/TonyProkop/",
    },
    {
      component: <Linkedin />,
      href: "https://www.linkedin.com/in/tony-prokop/",
    },
    {
      component: <RSS />,
      href: "",
    },
  ]

  return (
    <Box component="footer">
      <Container
        sx={{
          paddingBlock: 20,
        }}
      >
        <Typography
          variant="h2"
          sx={{
            color: "var(--clr-text)",
            fontSize: "6rem",
            fontWeight: "400",
          }}
        >
          <Headshot sx={{
            marginRight: 2,
            height: "1lh",
            width: "auto",
          }}
          />
          <span>
            Let&apos;s work
            <br />
            together
          </span>
        </Typography>
        <Box
          sx={{
            display: "flex",
            flexDirection: "row-reverse",
            position: "relative",
          }}
        >
          <PrimaryButton href="/contact">Get in touch</PrimaryButton>
          <Divider
            sx={{
              position: "absolute",
              left: 0,
              right: 0,
              top: "50%",
              transform: "translateY(-50%)",
              border: "1px solid var(--clr-muted)",
            }}
          />
        </Box>
        <ButtonGroup>
          <MagneticButton
            href="mailto:prokop.tony@gmail.com"
            strength={25}
            text-strength={15}
          >
            prokop.tony@gmail.com
          </MagneticButton>
          <MagneticButton
            href="tel:14029888222"
            strength={25}
            text-strength={15}
          >
            (402) 988-8222
          </MagneticButton>
        </ButtonGroup>
        <Stack spacing={2} alignItems="center" marginTop={20}>
          <Stack
            direction="row"
            justifyContent="center"
            spacing={4}
            sx={{ marginTop: 10, svg: { color: "var(--clr-subtle)" } }}
          >
            {links.map((l) => (
              <a href={l.href} key={l.href}>
                {l.component}
              </a>
            ))}
          </Stack>
          <Typography sx={{ color: "var(--clr-subtle)" }}>
            Tony Prokop @ 2024
          </Typography>
        </Stack>
      </Container>
    </Box>
  )
}

export default Footer
